# Aprendizagem Automática Avançada

**Alunos:**
    João Raimundo (57454), Rui Roque (57588)
    
    


## Assigment #3 - Mixture Models

### 0.1 - Import Libraries

In [90]:
# importação das bibliotecas
from sklearn.datasets import load_breast_cancer
from sklearn.linear_model import LogisticRegression, LinearRegression, BayesianRidge
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import AdaBoostClassifier, RandomForestClassifier
from sklearn.model_selection import train_test_split, KFold
from sklearn.metrics import classification_report, accuracy_score
from sklearn import svm
from sklearn.preprocessing import StandardScaler
from scipy.special import softmax
import numpy as np
from statistics import mean

### 0.2 - Importação dos Dados

In [91]:
# importação do conjunto de dados breast_cancer
x, y = load_breast_cancer(return_X_y=True)

x # features

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

### 0.3. Pré-processamento dos dados

Ao visualizar os dados de cima, procedeu-se à standardization das features

In [92]:
# features standardization
scaler = StandardScaler()
scaler.fit(x)
X_scaled = scaler.transform(x)

X_scaled

array([[ 1.09706398, -2.07333501,  1.26993369, ...,  2.29607613,
         2.75062224,  1.93701461],
       [ 1.82982061, -0.35363241,  1.68595471, ...,  1.0870843 ,
        -0.24388967,  0.28118999],
       [ 1.57988811,  0.45618695,  1.56650313, ...,  1.95500035,
         1.152255  ,  0.20139121],
       ...,
       [ 0.70228425,  2.0455738 ,  0.67267578, ...,  0.41406869,
        -1.10454895, -0.31840916],
       [ 1.83834103,  2.33645719,  1.98252415, ...,  2.28998549,
         1.91908301,  2.21963528],
       [-1.80840125,  1.22179204, -1.81438851, ..., -1.74506282,
        -0.04813821, -0.75120669]])

### 0.4. Definição de Funções

Definição de uma função (modelSelection) que faz KFold cross-validation, treinando os modelos e calculando as respetivas previsões e accuracy score.

In [93]:
def modelSelection(X_train, y_train, model, acc, predicts, i=1):
    kf = KFold(n_splits=5)
    
    TRUTH=None
    PREDS=None

    for train_index, test_index in kf.split(X_train):
        X_train_fold, X_test_fold = X_train[train_index], X_train[test_index]
        y_train_fold, y_test_fold = y_train[train_index], y_train[test_index]

        model.fit(X_train_fold,y_train_fold)
        preds = model.predict(X_test_fold)

        if TRUTH is None:
            PREDS=preds
            TRUTH=y_test_fold
        else:
            PREDS=np.hstack((PREDS, preds))
            TRUTH=np.hstack((TRUTH, y_test_fold))
    

    acc = np.append(acc, accuracy_score(TRUTH, PREDS))
    if(i == 0):
        predicts = np.append(predicts, PREDS)
    else:
        predicts = np.vstack((predicts, PREDS))
        
    return acc, predicts


### 0.5. Treino e Teste dos Modelos de Classificação (predictions e respetivos scores)

Seleção dos Melhores Modelos de Classificação:

 * LogisticRegression() 
 * DecisionTreeClassifier() - vários hyperparametros testados
 * svm.SVC()                - vários hyperparametros testados
 * RandomForestClassifier()

In [94]:
acc = []
preds = []

# seleção do melhor modelo de logistic regression
acc, preds = modelSelection(X_scaled, y, LogisticRegression(max_iter=10000), acc, preds, 0)

print(acc)
print(preds)

[0.9771529]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0.
 1. 1. 1. 1. 1. 0. 0. 1. 0. 0. 1. 1. 1. 1. 0. 1. 0. 0. 1. 1. 0. 1. 0. 1.
 0. 1. 1. 0. 1. 0. 0. 1. 1. 1. 0. 0. 1. 0. 0. 0. 1. 1. 1. 0. 1. 1. 0. 0.
 1. 1. 1. 0. 0. 1. 1. 1. 1. 0. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0.
 1. 0. 0. 1. 1. 1. 0. 0. 1. 0. 1. 0. 0. 1. 0. 1. 1. 1. 0. 1. 1. 0. 1. 1.
 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 0. 0. 1. 0. 1. 1. 0.
 0. 1. 1. 0. 0. 1. 1. 1. 1. 0. 1. 1. 0. 0. 0. 1. 0. 1. 0. 1. 1. 1. 1. 1.
 1. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 1. 0. 1. 1. 0. 1. 0. 1. 0. 1.
 1. 1. 0. 0. 1. 1. 1. 0. 1. 0. 1. 1. 1. 0. 0. 1. 1. 0. 1. 1. 0. 0. 1. 0.
 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.
 0. 0. 1. 1. 1. 1. 1. 1. 0. 1. 0. 1. 1. 0. 1. 1. 0. 1. 0. 0. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 0. 1. 1. 1. 0. 1. 0. 1.

In [95]:
# seleção do melhor modelo de Decision Tree Classifier com os hiperparâmetros default
acc, preds = modelSelection(X_scaled, y, DecisionTreeClassifier(), acc, preds)

print(acc)
print(preds)

[0.9771529  0.91212654]
[[0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]]


In [96]:
# seleção do melhor modelo de Decision Tree Classifier com o critério entropia
acc, preds = modelSelection(X_scaled, y, DecisionTreeClassifier(criterion="entropy"), acc, preds)

print(acc)

[0.9771529  0.91212654 0.93673111]


In [97]:
# seleção do melhor modelo de Decision Tree Classifier com o critério entropia e max_depth = 4
acc, preds = modelSelection(X_scaled, y, DecisionTreeClassifier(criterion="entropy", max_depth=4), acc, preds)

print(acc)

[0.9771529  0.91212654 0.93673111 0.94551845]


In [98]:
# seleção do melhor modelo de svm.SVC com os hiperparâmetros default 
acc, preds = modelSelection(X_scaled, y, svm.SVC(), acc, preds)

print(acc)

[0.9771529  0.91212654 0.93673111 0.94551845 0.97012302]


In [99]:
# seleção do melhor modelo de svm.SVC com kernel = poly
acc, preds = modelSelection(X_scaled, y, svm.SVC(kernel="poly"), acc, preds)

print(acc)

[0.9771529  0.91212654 0.93673111 0.94551845 0.97012302 0.89279438]


In [100]:
# seleção do melhor modelo de svm.SVC com kernel = rbf
acc, preds = modelSelection(X_scaled, y, svm.SVC(kernel="rbf"), acc, preds)

print(acc)

[0.9771529  0.91212654 0.93673111 0.94551845 0.97012302 0.89279438
 0.97012302]


In [101]:
# seleção do melhor modelo de RandomForest com n_estimators = 10
acc, preds = modelSelection(X_scaled, y, RandomForestClassifier(n_estimators=10), acc, preds)

print(acc)

[0.9771529  0.91212654 0.93673111 0.94551845 0.97012302 0.89279438
 0.97012302 0.94551845]


In [102]:
print(len(acc))
print(len(preds))

8
8


### 0.6. Weighted Average Ensemble System

Tendo em conta os scores de accuracy obtidos nos melhores modelos selecionados, aplicou-se a função softmax ao array de accuracies

In [103]:
acc = softmax(acc)
acc

array([0.12919497, 0.12106121, 0.12407681, 0.12517192, 0.12828993,
       0.11874331, 0.12828993, 0.12517192])

Aplicação do Weighted Average Ensemble System a partir da fórmula:

 - round(softmax([a1, a2, . . . , an]) · [f1(X), f2(X), . . . , fn(X)])

In [104]:
wae = np.around(np.dot(acc, preds), decimals=0)
wae

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 1., 1., 1.,
       1., 1., 0., 0., 1., 0., 0., 1., 1., 1., 1., 0., 1., 0., 0., 1., 1.,
       0., 1., 0., 1., 0., 1., 1., 0., 1., 0., 0., 1., 1., 1., 0., 0., 1.,
       0., 1., 0., 1., 1., 1., 1., 1., 1., 0., 0., 1., 1., 1., 1., 0., 1.,
       1., 1., 1., 0., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0.,
       0., 1., 0., 0., 1., 1., 1., 0., 0., 1., 0., 1., 0., 0., 1., 0., 1.,
       1., 1., 0., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 0., 0., 1., 1., 1., 0., 0., 1., 0., 1., 1., 0., 0., 1.,
       1., 0., 0., 1., 1., 1., 1., 0., 1., 1., 0., 0., 0., 1., 0., 1., 0.,
       1., 1., 1., 0., 1., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0.,
       1., 1., 1., 0., 1., 1., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 1.,
       1., 1., 0., 1., 1.

Com base no output do Weighted Average Ensemble System procedeu-se à avaliação do Mixture Model 

In [105]:
print(classification_report(y, wae))

              precision    recall  f1-score   support

           0       0.98      0.95      0.96       212
           1       0.97      0.99      0.98       357

    accuracy                           0.97       569
   macro avg       0.98      0.97      0.97       569
weighted avg       0.97      0.97      0.97       569

